library my_prj.globals;

bool isLoggedIn = true;
var userId;
var username;
var firstname;
var lastname;
var phone;
var cardNumber;
var carNumber;
var driverLicense;
// var carNumbevar;
var adminUserId;
var role;
var fuelStation;
var userAccAmt;
var amount;
var orderCode;
var stationLocation;
var companyName;
